[package]
name = "gasless_gossip"
version = "0.1.0"
edition = "2023_10"

[dependencies]
starknet = "2.4.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }

[lib]
sierra = true
casm = true

[[target.starknet-contract]]
sierra = true
casm = true

[tool.fmt]
sort-module-block-list = true
max-line-length = 100
tab-size = 4

[tool.snforge]
exit_first = false